#!/bin/bash

docker pull hub.alterway.fr/library/python:3.5 > /dev/null
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/src -w /src -e BACKEND=consul -e ORCHESTRATOR=swarm hub.alterway.fr/library/python:3.5 ./quality.py
